### ISSUE TITLE
machine breaks servers

### ISSUE THREAD

**Issue by Xplodin** [benbenlaw/essence-1.19.X#1]
https://gist.github.com/Xplodin/a65b45c7fe1f797df17d809da417582b

**Comment by benbenlaw** [comment]
what did you do when this happened?

**Comment by Xplodin** [comment]
trying to duplicate emeralds when using resource duplicator. the slots were acting strange as well idk if the correct slot was used or not but was following JEI recipe

**Comment by benbenlaw** [comment]
what version?

**Comment by Xplodin** [comment]
1.20.1 
 
 
  On Tue, Jul 18, 2023 at 10:25 AM, ***@***.***> wrote:   


what version?

**Comment by benbenlaw** [comment]
did you automatically do it or automation?

**Comment by Xplodin** [comment]
Manual input
Sent from Yahoo Mail on Android 
 
  On Tue, Jul 18, 2023 at 10:43 AM, ***@***.***> wrote:   


did you automatically do it or automation?

**Comment by benbenlaw** [comment]
ok so i may have found a couple of issues with the current way i was doing things, i was calling client sided things on the server

2.0.2 should fix the issue and your server should work again
